/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Idea = IDL.Record({
  'text' : IDL.Text,
  'tone' : IDL.Text,
  'category' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllIdeas' : IDL.Func([], [IDL.Vec(Idea)], ['query']),
  'getCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getRandomIdea' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Opt(Idea)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Idea = IDL.Record({
    'text' : IDL.Text,
    'tone' : IDL.Text,
    'category' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllIdeas' : IDL.Func([], [IDL.Vec(Idea)], ['query']),
    'getCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getRandomIdea' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Opt(Idea)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };